version: '3'

services:  
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .ok_env
    expose:
      - "8080"
  nginx:
    build:
      context: ./misc/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80


  redis:
    build: ./misc/redis
    ports:
      - "6379:6379"


  celery:
    build: ./celery_monitor
    env_file:
    - .ok_env
    depends_on:
      - redis