version: '3'

services:
    # web:
    #     build: ./api
    #     command: bash -c "python manage.py migrate && python manage.py flush --no-input && python manage.py runserver 0.0.0.0:8000"
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - db
    #         - redis

    redis:
        build: ./misc/redis
        ports:
            - "6379:6379"


    celery:
        build: ./celery_monitor
        depends_on:
            - redis